---
apiVersion: v1
kind: Namespace
metadata:
  name: tatsu
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: tatsu
  labels:
    tatsu.deployment: gateway
spec:
  ports:
  - port: 80
    name: gateway
  selector:
    tatsu.deployment: gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gateway
  namespace: tatsu
spec:
  serviceName: gateway
  replicas: 2
  selector:
    matchLabels:
      tatsu.deployment: gateway
  template:
    metadata:
      labels:
        tatsu.deployment: gateway
    spec:
      containers:
      - name: gateway
        image: rg.fr-par.scw.cloud/tatsu/gateway
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: FORCE_COLOR
            value: "1"
          - name: PLAYED
            value: "ws://played.tatsu.svc.cluster.local"
          - name: REDIS
            value: "10.64.132.51:6379"
          - name: ETCD
            value: "http://10.64.132.51:2379,http://10.64.132.51:2380"
          - name: PPROF
            value: "localhost:6060"
          - name: ADDR
            value: "0.0.0.0:80"
          - name: SHARDS
            value: "1024"
          - name: SHARDS_PER_POD
            value: "4"
      imagePullSecrets:
        - name: scalewayauth
