---
apiVersion: v1
kind: Namespace
metadata:
  name: tatsu
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: tatsu
  labels:
    app: gateway
spec:
  ports:
  - port: 80
    name: gateway
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gateway
  namespace: tatsu
spec:
  serviceName: gateway
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: rg.fr-par.scw.cloud/tatsu/gateway
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: redis
            value: "10.65.50.37:6379"
          - name: etcd
            value: "http://10.64.154.59:2379,http://10.64.154.59:2380"
          - name: pprof
            value: "localhost:6060"
          - name: addr
            value: "0.0.0.0:80"
          - name: shards
            value: "1000"
          - name: start
            value: "0"
          - name: stop
            value: "1"
      imagePullSecrets:
        - name: scalewayauth
