apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tatsu.deployment: state
  name: state
  namespace: tatsu
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      tatsu.deployment: state
  template:
    metadata:
      labels:
        tatsu.deployment: state
    spec:
      imagePullSecrets:
        - name: scalewayauth
      restartPolicy: Always
      containers:
        - name: state
          image: rg.fr-par.scw.cloud/tatsu/state
          imagePullPolicy: Always
          ports:
            - name: state
              containerPort: 80
          tty: true
          env:
            - name: FORCE_COLOR
              value: "1"
            - name: ADDR
              value: "0.0.0.0:80"
            - name: PSQL
              value: "postgresql://tatsu@10.0.0.3:5432/tatsu?sslmode=disable"
          livenessProbe:
            httpGet:
              path: /healthz
              port: statews
            initialDelaySeconds: 1
            failureThreshold: 4
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: state
  namespace: tatsu
spec:
  type: NodePort
  externalTrafficPolicy: "Local"
  selector:
    tatsu.deployment: state
  ports:
    - name: state
      port: 80
      protocol: TCP
---
